'use strict';
const client=window.supabase.createClient('https://gcksbfstheavpfgcdndb.supabase.co','eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdja3NiZnN0aGVhdnBmZ2NkbmRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc3NTA3MjcsImV4cCI6MjA5MzMyNjcyN30.5yqzDt5mTJRpTavKq4GJ0CwX6qT3GaVvXqbcdawJUmU');
const el=id=>document.getElementById(id);let employees=[],settings,localDocs=[],queueDocs=[],batches=[],driveLinks=[],selectedBatch=null,localBatchId=null,busy=false;let vacation=null;const vacationId=new URLSearchParams(location.search).get("ferias_periodo");
const labels={prepared:'Aguardando upload',uploading:'Enviando ao Drive',ready:'Pronto para aprovação',queued:'Aprovado, aguardando envio',sending:'Chamando n8n',accepted:'Aceito pelo n8n',uncertain:'Resultado incerto — confira n8n',failed:'Falha — revisão necessária',cancelled:'Cancelado'};
const workerUrl='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.min.mjs';
function notice(text,error=false){el('notice').textContent=text;el('notice').classList.toggle('error',error);}
async function action(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){notice(e.message||String(e),true);}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
const employee=id=>employees.find(e=>e.id===id);
function td(row,text){const c=document.createElement('td');c.textContent=text||'—';row.append(c);return c;}
function resetLocal(){localBatchId=null;localDocs.forEach(d=>d.objectUrl&&URL.revokeObjectURL(d.objectUrl));localDocs=[];el('preview').replaceChildren();}
function renderLocal(){el('preview').replaceChildren();localDocs.forEach(d=>{const r=document.createElement('tr'),c=td(r,''),check=document.createElement('input');check.type='checkbox';check.disabled=!!d.error||d.imported;check.checked=d.selected;check.onchange=()=>d.selected=check.checked;c.replaceChildren(check);td(r,d.employee?.nome);td(r,d.source+' · '+d.first+'–'+d.last);td(r,d.imported?'Importado':d.error||'Pronto');const a=document.createElement('a');a.href=d.objectUrl;a.download=d.filename;a.textContent='Conferir PDF';td(r,'').replaceChildren(a);el('preview').append(r);});}
el('analyze').onclick=()=>action(async()=>{
 const files=[...(el('pdfFiles').files.length?el('pdfFiles').files:el('pdfFolder').files)].filter(f=>/\.pdf$/i.test(f.name));const count=Number(el('pages').value);
 if(!files.length||!Number.isInteger(count)||count<1||count>100)throw Error('Escolha PDFs e uma quantidade válida de páginas.');
 if(!/^(0[1-9]|1[0-2])\/\d{4}$/.test(el('competence').value))throw Error('Informe a competência em MM/AAAA.');
 resetLocal();const pdfjs=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc=workerUrl;
 for(const file of files){
  if(file.size>30*1024*1024)throw Error(file.name+': origem maior que 30 MB. Divida o lote.');
  notice('Analisando '+file.name+'…');const bytes=new Uint8Array(await file.arrayBuffer());let readable,source;
  try{readable=await pdfjs.getDocument({data:bytes.slice(),isEvalSupported:false}).promise;source=await PDFLib.PDFDocument.load(bytes,{updateMetadata:false});}catch(e){throw Error(file.name+': PDF protegido ou inválido. Desbloqueie antes de importar.');}
  if(readable.numPages>1000||readable.numPages%count)throw Error(file.name+': total de páginas incompatível com o agrupamento.');
  for(let first=0;first<readable.numPages;first+=count){
   let identified=null,error='';
   try{const identities=[];for(let i=first;i<first+count;i++){const page=await readable.getPage(i+1),text=(await page.getTextContent()).items.map(v=>v.str).join(' ');identities.push(RHDocuments.identify(text,employees));}if(new Set(identities.map(e=>e.id)).size!==1)throw Error('Grupo contém colaboradores diferentes.');identified=identities[0];if(vacation&&identified.id!==vacation.funcionario_id)throw Error('PDF pertence a outro colaborador: revise o vínculo de férias.');if(vacation&&!['AVISO DE FERIAS','RECIBO DE FERIAS','COMPROVANTE ASSINADO'].includes(el('kind').value))throw Error('Selecione um tipo de documento de férias.');RHDocuments.phone(identified.whatsapp);}catch(e){error=e.message;}
   const out=await PDFLib.PDFDocument.create();const pages=await out.copyPages(source,Array.from({length:count},(_,i)=>first+i));pages.forEach(p=>out.addPage(p));out.setCreationDate(new Date('2000-01-01T00:00:00Z'));out.setModificationDate(new Date('2000-01-01T00:00:00Z'));const result=await out.save();
   const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',result))].map(b=>b.toString(16).padStart(2,'0')).join('');const id=crypto.randomUUID();const filename=(identified?.nome||'REVISAR').replace(/[^\p{L}\p{N} ._-]/gu,'_').slice(0,100)+'_'+el('kind').value+'_'+el('competence').value.replace('/','-')+'.pdf';
   localDocs.push({id,employee:identified,error:error||(result.byteLength>10485760?'PDF separado excede 10 MB':''),source:file.name,first:first+1,last:first+count,bytes:result,sha256:hash,filename,kind:el('kind').value,period:el('competence').value,objectUrl:URL.createObjectURL(new Blob([result],{type:'application/pdf'})),selected:false,imported:false});
  }
  await readable.destroy();
 }
 renderLocal();notice(localDocs.length+' documentos preparados localmente. Confira os PDFs e selecione quem deseja importar.');
});
el('all').onclick=()=>{localDocs.forEach(d=>d.selected=!d.error&&!d.imported);renderLocal();};el('none').onclick=()=>{localDocs.forEach(d=>d.selected=false);renderLocal();};
el('upload').onclick=()=>action(async()=>{
 const selected=localDocs.filter(d=>d.selected&&!d.error&&!d.imported);if(!selected.length)throw Error('Selecione documentos prontos.');
 if(!confirm('Importar '+selected.length+' PDFs selecionados para armazenamento privado e fila de upload do Drive? Nenhuma mensagem será enviada nesta etapa.'))return;
 let batchId=localBatchId;
 for(const d of selected){
  const duplicate=await RH.result(client.from('rh_delivery_documents').select('id,status').eq('funcionario_id',d.employee.id).eq('document_type',d.kind).eq('period',d.period).eq('sha256',d.sha256));
  if(duplicate.length){d.imported=true;d.selected=false;continue;}
  if(!batchId)localBatchId=batchId=await RH.result(client.rpc('rh_create_delivery_batch',{p_name:el('batchName').value.trim()||d.kind+' · '+d.period+' · '+new Date().toLocaleString('pt-BR'),p_type:d.kind,p_period:d.period}));
  const path=d.id+'.pdf';const {error}=await client.storage.from('rh-documentos').upload(path,new Blob([d.bytes],{type:'application/pdf'}),{contentType:'application/pdf',upsert:false});if(error)throw error;
  try{await RH.result(client.from('rh_delivery_documents').insert({id:d.id,funcionario_id:d.employee.id,document_type:d.kind,period:d.period,filename:d.filename,sha256:d.sha256,storage_path:path,batch_id:batchId,...(vacation?{vacation_period_id:vacation.id}:{})}).select(),true);}catch(e){await client.storage.from('rh-documentos').remove([path]);throw e;}
  d.imported=true;d.selected=false;renderLocal();
 }
 if(!batchId){await refresh();notice('Os PDFs selecionados já constam no histórico; nenhum lote duplicado foi criado.');return;}selectedBatch=batchId;await refresh();notice('Documentos importados. Ative o processamento de uploads e acompanhe. O envio ao n8n requer aprovação posterior.');
});
function batchDocs(){return queueDocs.filter(d=>(d.batch_id||'no-batch')===selectedBatch);}
function batchStats(docs){const counts={};docs.forEach(d=>counts[d.status]=(counts[d.status]||0)+1);return docs.length+' documentos · '+(counts.ready||0)+' prontos · '+(counts.failed||0)+' com falha · '+(counts.prepared||0)+' aguardando upload · '+(counts.uploading||0)+' em upload · '+((counts.queued||0)+(counts.sending||0))+' em envio · '+(counts.accepted||0)+' aceitos pelo n8n'+(counts.uncertain?' · '+counts.uncertain+' incertos':'');}
function renderBatches(){const list=batches.slice();if(queueDocs.some(d=>!d.batch_id))list.push({id:'no-batch',name:'Documentos sem lote / anexados por link',created_at:queueDocs.find(d=>!d.batch_id).created_at,legacy:true});el('batches').replaceChildren();list.sort((a,b)=>b.created_at.localeCompare(a.created_at)).forEach(b=>{const card=document.createElement('article');card.className='batch-card';const h=document.createElement('h3');h.textContent=b.name;const date=document.createElement('p');date.textContent=new Date(b.created_at).toLocaleString('pt-BR')+' · '+(b.document_type||'Documentos')+' · '+(b.period||'');const stats=document.createElement('p');stats.textContent=batchStats(queueDocs.filter(d=>(d.batch_id||'no-batch')===b.id));const open=document.createElement('button');open.textContent='Abrir lote e conferir documentos';open.onclick=()=>{selectedBatch=b.id;renderQueue();el('batchDetail').scrollIntoView({behavior:'smooth',block:'start'});};card.append(h,date,stats);if(b.legacy){const note=document.createElement('small');note.textContent='Agrupamento de registros anteriores; a identificação original do lote não era armazenada.';card.append(note);}card.append(open);el('batches').append(card);});if(!list.length)el('batches').textContent='Nenhum lote importado.';}
function pdfButton(d){const b=document.createElement('button');b.textContent='Conferir / baixar PDF';b.onclick=()=>action(async()=>{if(d.source==='link'){window.open(d.link,'_blank','noopener');return;}const {data,error}=await client.storage.from('rh-documentos').createSignedUrl(d.storage_path,120);if(error)throw error;if(!data?.signedUrl)throw Error('PDF privado não disponível');const a=document.createElement('a');a.href=data.signedUrl;a.target='_blank';a.rel='noopener';a.click();notice('PDF aberto por link temporário privado. O arquivo permanece no lote.');});return b;}
function renderQueue(){el('batchDetail').hidden=!selectedBatch;el('queue').replaceChildren();if(!selectedBatch)return;const docs=batchDocs(),b=batches.find(b=>b.id===selectedBatch);el('batchTitle').textContent=b?.name||'Documentos sem lote';const missing=new Set(docs.filter(d=>d.status!=='cancelled'&&!driveLinks.some(l=>l.funcionario_id===d.funcionario_id&&!l.template_pending)).map(d=>d.funcionario_id));el('batchSummary').textContent=batchStats(docs)+(missing.size?' · '+missing.size+' colaborador(es) com pasta pendente de vínculo/processamento':'');
 docs.forEach(d=>{const r=document.createElement('tr'),e=employee(d.funcionario_id),c=td(r,''),check=document.createElement('input');check.type='checkbox';check.disabled=d.status!=='ready';check.checked=!!d.selected;check.onchange=()=>d.selected=check.checked;c.replaceChildren(check);let phone;try{phone=RHDocuments.phone(e?.whatsapp);}catch(_){phone='WhatsApp inválido';}td(r,(e?.nome||'Cadastro indisponível')+'\n'+phone);td(r,d.document_type+' · '+d.period);td(r,labels[d.status]+(d.error?'\n'+d.error:''));const box=td(r,''),input=document.createElement('input');input.type='url';input.value=d.editLink||d.link||'';input.placeholder='Link acessível ao colaborador';input.disabled=d.status!=='ready';const preview=document.createElement('pre');preview.style.whiteSpace='pre-wrap';const draw=()=>{try{d.preview=RHDocuments.message(el('template').value,{nome:e?.nome,tipo:d.document_type,competencia:d.period,link:input.value});preview.textContent=d.preview;}catch(error){preview.textContent=error.message;}};input.oninput=()=>{d.editLink=input.value;draw();};box.replaceChildren(input,preview);draw();const actions=td(r,''),buttons=document.createElement('div');buttons.className='document-actions';buttons.append(pdfButton(d));if(d.link){const a=document.createElement('a');a.href=d.link;a.target='_blank';a.rel='noopener';a.textContent='Abrir no Drive / portal';buttons.append(a);}if(d.status==='failed'&&d.source!=='link'){const b=document.createElement('button');b.textContent='Retomar upload';b.onclick=()=>action(async()=>{if(!confirm('Retomar o upload deste PDF existente, sem autorizar mensagem?'))return;await RH.result(client.rpc('rh_retry_document_upload',{p_id:d.id}));await refresh();notice('Upload retomado. Aguarde o processador; nenhum envio foi autorizado.');});buttons.append(b);}if(['prepared','ready','queued','failed'].includes(d.status)){const b=document.createElement('button');b.textContent='Cancelar';b.onclick=()=>action(async()=>{if(confirm('Cancelar este documento da fila? O arquivo existente no Drive será preservado.')){await RH.result(client.rpc('rh_cancel_delivery',{p_id:d.id}));await refresh();}});buttons.append(b);}actions.append(buttons);el('queue').append(r);});}
async function refresh(){settings=await RH.result(client.from('rh_automation_settings').select('*').eq('id',true).single(),true);[queueDocs,batches,driveLinks]=await Promise.all([RH.fetchAll(client,'rh_delivery_documents'),RH.fetchAll(client,'rh_delivery_batches'),RH.fetchAll(client,'rh_drive_links','*','funcionario_id')]);el('worker').textContent=settings.last_documents_worker_at?'Último contato: '+new Date(settings.last_documents_worker_at).toLocaleString('pt-BR'):'Processador ainda não instalado. Siga as instruções.';el('documentsEnabled').checked=settings.documents_enabled;el('sendEnabled').checked=settings.n8n_enabled;renderBatches();renderQueue();}
el('closeBatch').onclick=()=>{selectedBatch=null;renderQueue();};
el('prepareFolders').onclick=()=>action(async()=>{const ids=[...new Set(batchDocs().filter(d=>d.status!=='cancelled'&&!driveLinks.some(l=>l.funcionario_id===d.funcionario_id&&!l.template_pending)).map(d=>d.funcionario_id))];if(!ids.length){notice('As pastas deste lote já estão vinculadas e processadas.');return;}if(!settings.drive_enabled)throw Error('Ative a automação de pastas na página Automações primeiro.');if(settings.drive_worker_version!=='existing-link-v1')throw Error('Atualize RH_Drive_Automacoes.gs pelo GitHub e execute instalarAutomacaoDriveRH antes de vincular pastas em lote.');if(!confirm('Vincular '+ids.length+' pastas existentes pelo nome/CPF? Não criará, moverá ou renomeará pastas. Correspondências ambíguas precisarão de vínculo manual. Não enviará mensagens.'))return;let done=0;try{for(const id of ids){if(employee(id)?.data_desligamento)continue;await RH.result(client.rpc('rh_link_existing_drive',{p_employee:id}));done++;}}finally{await refresh();notice(done+' pasta(s) colocadas na fila. Aguarde o gatilho de pastas (até 5 minutos), atualize e então retome os uploads com falha.');}});
el('retryUploads').onclick=()=>action(async()=>{const docs=batchDocs().filter(d=>d.status==='failed'&&d.source!=='link'&&!d.approved_at&&driveLinks.some(l=>l.funcionario_id===d.funcionario_id&&!l.template_pending));if(!docs.length){notice('Nenhuma falha de upload pronta para retomada. Processe primeiro as pastas pendentes e atualize.');return;}if(!confirm('Retomar '+docs.length+' uploads usando os PDFs já importados? Nenhuma mensagem será autorizada.'))return;let done=0;try{for(const d of docs){await RH.result(client.rpc('rh_retry_document_upload',{p_id:d.id}));done++;}}finally{await refresh();notice(done+' upload(s) retomado(s). Aguarde ficarem prontos e confira os PDFs antes de autorizar mensagens.');}});
el('save').onclick=()=>action(async()=>{await RH.result(client.from('rh_automation_settings').update({documents_enabled:el('documentsEnabled').checked,n8n_enabled:el('sendEnabled').checked}).eq('id',true).select(),true);await refresh();notice('Ativação salva. Somente mensagens aprovadas podem entrar no envio.');});
el('refresh').onclick=()=>action(refresh);el('template').oninput=renderQueue;
el('selectReady').onclick=()=>{const docs=batchDocs();queueDocs.forEach(d=>d.selected=false);docs.forEach(d=>d.selected=d.status==='ready');renderQueue();const count=docs.filter(d=>d.selected).length;notice(count?count+' documento(s) pronto(s) selecionado(s) neste lote.':'Nenhum documento pronto neste lote. Confira as falhas e o vínculo das pastas; selecionar não retoma uploads.');};
el('approve').onclick=()=>action(async()=>{const selected=batchDocs().filter(d=>d.selected&&d.status==='ready');if(!selected.length)throw Error('Selecione documentos prontos para aprovação.');if(!confirm('Autorizar '+selected.length+' mensagens? Confirme que conferiu os destinatários, PDFs, texto e acesso dos colaboradores aos links.'))return;for(const d of selected){const link=d.editLink||d.link;const u=new URL(link);if(u.protocol!=='https:')throw Error('Use link HTTPS');await RH.result(client.rpc('rh_approve_delivery',{p_id:d.id,p_link:link,p_message:d.preview}));}await refresh();notice('Mensagens autorizadas e colocadas na fila. Acompanhe a confirmação do n8n.');});
action(async()=>{const p=await RH.profile(client);if(p.status!=='admin')throw Error('Acesso restrito ao administrador');employees=await RH.fetchAll(client,'funcionarios_epi','id,nome,cpf,whatsapp,data_desligamento');if(vacationId){vacation=await RH.result(client.from('rh_ferias_periodos').select('*').eq('id',vacationId).single(),true);el('vacationContext').hidden=false;el('vacationContext').textContent='Vincular documentos a '+employee(vacation.funcionario_id)?.nome+' · período aquisitivo '+vacation.inicio.split('-').reverse().join('/')+' a '+vacation.fim.split('-').reverse().join('/')+'. Somente PDFs identificados para este colaborador serão aceitos.';el('kind').value='AVISO DE FERIAS';}settings=await RH.result(client.from('rh_automation_settings').select('*').eq('id',true).single(),true);el('template').value=settings.message_template;await refresh();el('app').hidden=false;notice('Pronto para importar PDFs. Nenhuma mensagem será enviada sem sua aprovação.');});
