'use strict';
const client=window.supabase.createClient('https://gcksbfstheavpfgcdndb.supabase.co','eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdja3NiZnN0aGVhdnBmZ2NkbmRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc3NTA3MjcsImV4cCI6MjA5MzMyNjcyN30.5yqzDt5mTJRpTavKq4GJ0CwX6qT3GaVvXqbcdawJUmU');
const $=id=>document.getElementById(id),V=RHVacations;let employees=[],periods=[],launches=[],documents=[],deliveries=[],events=[],legacy=[],profile,currentEmployee,busy=false,onSubmit;
const statusNames={programado:'Programado',concluido:'Gozo confirmado',cancelado:'Cancelado / estornado'},deliveryNames={prepared:'Aguardando upload',uploading:'Upload em andamento',ready:'Pronto para autorização',queued:'Na fila de envio',sending:'Chamando n8n',accepted:'Aceito pelo n8n',uncertain:'Envio incerto — conferir n8n',failed:'Falha — revisar',cancelled:'Envio cancelado'};
function make(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function message(s,error=false){$('notice').textContent=s;$('notice').classList.toggle('error',error);}
async function action(fn){if(busy)return;busy=true;try{await fn();}catch(e){message(e.message||String(e),true);if($('formDialog').open){$('formError').hidden=false;$('formError').textContent=e.message||String(e);}}finally{busy=false;$('submitForm').disabled=false;}}
async function mutate(action,payload){return RH.result(client.rpc('rh_vacation_mutate',{p_action:action,p_payload:payload}));}
async function documentAction(action,payload){return RH.result(client.rpc('rh_vacation_document',{p_action:action,p_payload:payload}));}
function btn(label,fn,secondary=false){const b=make('button',label,secondary?'secondary':'');b.type='button';b.onclick=fn;return b;}
function link(label,url,cls){const a=make('a',label,cls);a.href=url;a.target='_blank';a.rel='noopener';return a;}
function metric(parent,label,value){const d=make('div',undefined,'metric');d.append(make('strong',value),make('small',label));parent.append(d);}
function state(e){const line=V.timeline(e,periods,RH.today()),ownLaunch=launches.filter(l=>line.some(p=>p.id===l.periodo_id)&&l.status==='programado'),forming=line.find(p=>p.phase==='em_formacao'),acquired=line.filter(p=>p.phase==='adquirido'&&p.id),balance=acquired.reduce((n,p)=>n+V.totals(p,launches).balance,0),missing=line.filter(p=>p.phase==='adquirido'&&!p.id).length,review=line.some(p=>p.review||(p.id&&(p.gozo_base>0||p.abono_base>0)))||missing>0||!V.parse(e.admissao);return {line,forming,balance,ownLaunch,missing,review};}
async function refresh(){const tables=['funcionarios_epi','rh_ferias_periodos','rh_ferias_lancamentos','rh_ferias_documentos','rh_delivery_documents','rh_ferias_eventos','rh_ferias'];[employees,periods,launches,documents,deliveries,events,legacy]=await Promise.all(tables.map(t=>RH.fetchAll(client,t,'*',t==='rh_ferias_eventos'?'id':'id')));renderSummary();if(currentEmployee){currentEmployee=employees.find(e=>e.id===currentEmployee.id);if(currentEmployee)renderHistory();}}
function renderSummary(){let all=employees.map(e=>({...e,info:state(e)}));const active=all.filter(e=>!e.data_desligamento);$('totalBalance').textContent=active.reduce((n,e)=>n+e.info.balance,0)+' d';$('totalSchedules').textContent=active.reduce((n,e)=>n+e.info.ownLaunch.length,0);$('totalReview').textContent=active.filter(e=>e.info.review).length;
 const unlinked=legacy.filter(f=>!f.funcionario_id);$('legacyWarning').hidden=!unlinked.length;$('legacyWarning').textContent=unlinked.length+' resumo(s) anterior(es) sem vínculo com colaborador. Corrija o vínculo no cadastro antes de controlar esse histórico.';
 const search=$('search').value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase(),filter=$('employeesFilter').value,status=$('statusFilter').value;
 all=all.filter(e=>(filter==='todos'||(filter==='ativos'?!e.data_desligamento:!!e.data_desligamento))&&((e.nome+' '+(e.cpf||'')).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().includes(search))&&(status==='todos'||status==='saldo'&&e.info.balance>0||status==='programadas'&&e.info.ownLaunch.length>0||status==='revisao'&&e.info.review)).sort((a,b)=>a.nome.localeCompare(b.nome,'pt-BR'));
 $('employees').replaceChildren();all.forEach(e=>{const {info}=e,r=make('tr');const cell=(label)=>{const c=make('td');c.dataset.label=label;r.append(c);return c;};cell('Colaborador').append(make('strong',e.nome),make('small',RH.cleanCpf(e.cpf)||'CPF não informado'),...(e.data_desligamento?[make('small','Desligado em '+V.format(e.data_desligamento))]:[]));const balance=cell('Saldo registrado');balance.append(make('strong',info.balance+' dias'),make('small',info.missing?info.missing+' período(s) anterior(es) sem registro':'Somente períodos adquiridos cadastrados'));
 const formation=cell('Em formação');if(info.forming){const a=V.accrual(info.forming.inicio,info.forming.fim,RH.today(),info.forming.direito??30);formation.append(make('span',V.format(info.forming.inicio)+' → '+V.format(info.forming.fim)),make('small',a.months+'/12 meses · '+a.days+' d de provisão estimada'));}else formation.append(make('small',V.parse(e.admissao)?'Nenhum período em formação':'Admissão inválida — revisar'));
 const next=info.ownLaunch.filter(l=>l.inicio).sort((a,b)=>a.inicio.localeCompare(b.inicio))[0];cell('Próxima saída').append(make('span',next?V.format(next.inicio):'Não programada'),make('small',next?next.dias_gozo+' d · retorno '+V.format(V.addDays(next.fim,1)):info.review?'Conferir histórico':'—'));
 cell('Histórico').append(btn('Histórico e registros',()=>openHistory(e)));$('employees').append(r);});$('empty').hidden=!!all.length;
}
function openHistory(e){currentEmployee=e;renderHistory();$('historyDialog').showModal();}
function renderHistory(){const e=currentEmployee,info=state(e);$('historyTitle').textContent=e.nome;$('historySubtitle').textContent='Admissão: '+V.format(e.admissao)+' · CPF: '+(RH.cleanCpf(e.cpf)||'não informado');$('timelineNotice').textContent='Períodos calculados pela admissão. Sem registro não significa que as férias não foram tiradas: informe os comprovantes e as datas reais. Próximos períodos aparecem automaticamente conforme o calendário.';$('periods').replaceChildren();
 if(!V.parse(e.admissao))$('timelineNotice').textContent+=' A admissão precisa ser corrigida no cadastro.';
 info.line.forEach(p=>{const card=make('article',undefined,'period-card'+(p.phase==='em_formacao'?' current':'')),heading=make('div',undefined,'period-heading');heading.append(make('h3',p.inicio.slice(0,4)+'–'+p.fim.slice(0,4)+' · '+V.format(p.inicio)+' a '+V.format(p.fim)));const phase=p.phase==='futuro'?'Próximo período':p.phase==='em_formacao'?'Em formação':p.id&&V.totals(p,launches).balance===0?'Quitado':'Adquirido';heading.append(make('span',phase,'badge'));card.append(heading);
 if(!p.id){card.append(make('p',p.phase==='futuro'?'Início previsto em '+V.format(p.inicio)+'. Nenhum saldo adquirido nesse período.':'Sem cadastro de direito ou gozo. As datas estão calculadas; selecione este período para registrar as informações reais.','subtle'));card.append(btn(p.phase==='futuro'?'Programar para este período':'Registrar férias deste período',()=>launchForm(p)));$('periods').append(card);return;}
 const t=V.totals(p,launches),metrics=make('div',undefined,'metrics');metric(metrics,'Direito confirmado',p.direito+' d');metric(metrics,'Gozados',t.used+' d');metric(metrics,'Abono',t.sold+' d');metric(metrics,'Saldo '+(p.phase!=='adquirido'?'do cadastro (a adquirir)':'registrado'),t.balance+' d');metric(metrics,'Reservados',t.reserved+' d');metric(metrics,'Disponíveis para lançamento',t.available+' d');card.append(metrics);
 const deadline=make('p','Prazo concessivo de referência: '+V.format(p.prazo_concessivo)+(p.prazo_concessivo<RH.today()&&t.balance>0?' · Prazo ultrapassado — revisar':'') ,'subtle');card.append(deadline);
 if(p.review){card.append(make('p','Conferir com DP: datas/prazo do resumo anterior diferem da referência anual. Prazo recebido: '+V.format(p.prazo_legado)+'. As informações originais foram preservadas.','badge warning'));}
 if(p.gozo_base||p.abono_base)card.append(make('p','Resumo anterior: '+p.gozo_base+' d gozados e '+p.abono_base+' d abonados. Esses totais já entram no saldo. Para detalhar as datas sem duplicar dias, revise primeiro o resumo anterior.','notice'));
 if(p.observacao)card.append(make('p',p.observacao,'subtle'));
 const tools=make('div',undefined,'row');tools.append(btn('Registrar / programar férias',()=>launchForm(p)),btn('Revisar direito e resumo anterior',()=>adjustForm(p),true));card.append(tools);
 const list=t.items.concat(launches.filter(l=>l.periodo_id===p.id&&l.status==='cancelado'));if(!list.length)card.append(make('p','Nenhuma saída com datas registrada neste período.','subtle'));
 list.sort((a,b)=>(a.inicio||a.created_at).localeCompare(b.inicio||b.created_at)).forEach(l=>{const item=make('div',undefined,'entry');item.append(make('strong',statusNames[l.status]+' · '+l.dias_gozo+' d de gozo · '+l.dias_abono+' d de abono'),make('p',l.inicio?V.format(l.inicio)+' a '+V.format(l.fim)+' · retorno '+V.format(V.addDays(l.fim,1)):'Abono sem saída informada'));if(l.observacao)item.append(make('small',l.observacao));const actions=make('div',undefined,'row');if(l.status==='programado'){actions.append(btn('Confirmar gozo concluído',()=>action(async()=>{if(!confirm('Confirmar que estes dias foram efetivamente gozados?'))return;await mutate('concluir',{id:l.id,observacao:'Gozo conferido pelo RH'});await refresh();message('Gozo confirmado. O período e as datas anteriores permanecem no histórico.');})));}
 if(l.status!=='cancelado')actions.append(btn('Estornar / cancelar',()=>cancelForm(l),true));actions.append(btn('Anexar aviso / recibo',()=>documentForm(p,l),true));item.append(actions);card.append(item);});
 card.append(make('h4','Documentos e devolução assinada'));const docs=documents.filter(d=>d.periodo_id===p.id);docs.forEach(d=>{const item=make('div',undefined,'document'),delivery=deliveries.find(x=>x.id===d.delivery_id);item.append(make('strong',d.tipo),make('p',d.assinatura_status==='recebido_assinado'?'Arquivo assinado recebido e registrado pelo RH':'Aguardando devolução assinada'),link('Abrir documento',d.link));if(d.signed_link)item.append(make('span',' · '),link('Abrir devolução assinada',d.signed_link));if(delivery)item.append(make('p','Envio: '+deliveryNames[delivery.status]));const actions=make('div',undefined,'row');if(profile.status==='admin'&&d.tipo!=='COMPROVANTE ASSINADO'&&(!delivery||delivery.status==='ready'))actions.append(btn('Conferir e autorizar WhatsApp',()=>sendForm(p,d)));if(d.assinatura_status!=='recebido_assinado')actions.append(btn('Registrar devolução assinada',()=>signedForm(d),true));item.append(actions,make('small','Recebimento manual não valida assinatura certificada.'));card.append(item);});
 const docTools=make('div',undefined,'row');docTools.append(btn('Anexar link de documento',()=>documentForm(p),true));if(profile.status==='admin')docTools.append(link('Importar PDF do computador','documentos-web.html?ferias_periodo='+p.id,'action-link'));card.append(docTools);if(!docs.length)card.append(make('p','Nenhum documento vinculado.','subtle'));$('periods').append(card);
 });
 const ids=new Set(info.line.map(p=>p.id));const ownEvents=events.filter(ev=>ids.has(ev.registro_id)||launches.some(l=>l.id===ev.registro_id&&ids.has(l.periodo_id))||documents.some(d=>d.id===ev.registro_id&&ids.has(d.periodo_id))).sort((a,b)=>b.created_at.localeCompare(a.created_at)).slice(0,50);$('audit').replaceChildren(...ownEvents.map(ev=>make('div',new Date(ev.created_at).toLocaleString('pt-BR')+' · '+ev.tabela.replace('rh_ferias_','')+' · '+ev.acao+' · '+(ev.actor_id?'Usuário autenticado':'Importação / serviço'),'audit-row')));
}
function form(title,submit){$('submitForm').textContent='Salvar';$('formTitle').textContent=title;$('formFields').replaceChildren();$('formError').hidden=true;onSubmit=submit;$('formDialog').showModal();}
function field(name,label,type='text',value='',options){const div=make('div',undefined,'field'),lab=make('label',label);lab.htmlFor='field-'+name;let input=make(options?'select':type==='textarea'?'textarea':'input');if(options)options.forEach(([v,t])=>{const o=make('option',t);o.value=v;input.append(o);});else if(type!=='textarea')input.type=type;input.id='field-'+name;input.name=name;input.value=value;if(type==='checkbox')input.checked=!!value;div.append(lab,input);$('formFields').append(div);return input;}
function values(){return Object.fromEntries(new FormData($('editForm')));}
function note(s){$('formFields').append(make('p',s,'subtle'));}
function launchForm(selected){const choices=state(currentEmployee).line;form('Registrar férias por período aquisitivo',async()=>{const data=values(),p=choices.find(p=>p.inicio===data.periodo);const payload={periodo_id:p.id||null,novo_periodo:p.id?undefined:{funcionario_id:currentEmployee.id,inicio:p.inicio,fim:p.fim,direito:Number(data.direito),observacao:'Período calculado pela admissão e direito confirmado pelo RH'},inicio:data.inicio,dias_gozo:Number(data.dias_gozo),dias_abono:Number(data.dias_abono),status:data.status,observacao:data.observacao,concordancia:$('field-concordancia').checked};await mutate('lancamento',payload);await saved('Lançamento registrado no período selecionado. Nenhuma mensagem foi enviada.');});
 const choice=field('periodo','Período aquisitivo','select',selected.inicio,choices.map(p=>[p.inicio,p.inicio.slice(0,4)+'–'+p.fim.slice(0,4)+' · '+V.format(p.inicio)+' a '+V.format(p.fim)+(p.id?'':' · sem registro')]));const start=field('periodo_inicio','Início aquisitivo preenchido automaticamente','date',selected.inicio),end=field('periodo_fim','Fim aquisitivo preenchido automaticamente','date',selected.fim);start.readOnly=end.readOnly=true;const right=field('direito','Direito do período (confirme com DP)','select',selected.direito??30,[0,12,18,24,30].map(d=>[d,d+' dias']));const capacity=make('p','', 'notice');$('formFields').append(capacity);const sync=()=>{const p=choices.find(p=>p.inicio===choice.value);start.value=p.inicio;end.value=p.fim;right.value=p.direito??30;right.disabled=!!p.id;capacity.textContent=p.id?'Saldo disponível para lançamento: '+V.totals(p,launches).available+' d (já descontadas as reservas).':'Período sem registro: o direito será cadastrado junto com este lançamento. Nenhum gozo anterior será inventado.';};choice.onchange=sync;sync();
 field('status','Situação','select',selected.phase==='adquirido'?'concluido':'programado',[['programado','Programar — reservar dias'],['concluido','Registrar gozo já concluído']]);field('inicio','Data em que as férias começam / começaram','date');const days=field('dias_gozo','Dias corridos de gozo','number',30);days.min=0;days.max=30;const sold=field('dias_abono','Dias convertidos em abono','number',0);sold.min=0;sold.max=10;field('concordancia','Concordância do colaborador registrada (fracionamento)','checkbox',false);field('observacao','Observação / referência do comprovante','textarea');note('Gozo concluído exige término anterior a hoje. Programações reservam dias, mas só entram em “gozados” após sua confirmação. Confira aviso prévio, pagamento, repouso semanal/feriados e regras aplicáveis com o DP.');}
function adjustForm(p){form('Revisar direito e totais anteriores',async()=>{const v=values();await mutate('ajustar',{periodo_id:p.id,direito:Number(v.direito),gozo_base:Number(v.gozo_base),abono_base:Number(v.abono_base),observacao:v.observacao});await saved('Resumo revisado com histórico da alteração.');});field('direito','Direito confirmado','select',p.direito,[0,12,18,24,30].map(n=>[n,n+' dias']));field('gozo_base','Dias gozados do resumo anterior, sem detalhamento de datas','number',p.gozo_base);field('abono_base','Dias de abono do resumo anterior','number',p.abono_base);field('observacao','Justificativa obrigatória (mínimo 10 caracteres)','textarea');note('Para substituir um total antigo por registros com datas, reduza o total de origem e lance os dias detalhados. Os lançamentos novos permanecem preservados; o sistema impede exceder o direito.');}
function periodForm(){form('Registrar período excepcional',async()=>{const v=values();await mutate('periodo',{funcionario_id:currentEmployee.id,inicio:v.inicio,fim:v.fim,direito:Number(v.direito),observacao:v.observacao});await saved('Período excepcional registrado.');});field('inicio','Início aquisitivo','date');field('fim','Fim aquisitivo','date');field('direito','Direito confirmado','select',30,[0,12,18,24,30].map(n=>[n,n+' dias']));field('observacao','Motivo e referência da validação do DP','textarea');note('Use a seleção automática por ano para períodos normais. Este formulário é reservado para datas excepcionais; ele não recalcula automaticamente efeitos de afastamentos.');}
function cancelForm(l){form('Cancelar / estornar lançamento',async()=>{await mutate('cancelar',{id:l.id,observacao:values().observacao});await saved('Lançamento cancelado; o registro permanece no histórico.');});field('observacao','Motivo obrigatório (mínimo 10 caracteres)','textarea');note('Um lançamento concluído será estornado do saldo. O histórico original e os documentos serão preservados.');}
function documentForm(p,l){form('Anexar aviso, recibo ou comprovante',async()=>{const v=values();await documentAction('anexar',{periodo_id:p.id,lancamento_id:v.lancamento_id||null,tipo:v.tipo,link:v.link,observacao:v.observacao});await saved('Documento vinculado ao período. Nenhuma mensagem foi enviada.');});const own=launches.filter(x=>x.periodo_id===p.id&&x.status!=='cancelado');field('lancamento_id','Vincular à saída / programação','select',l?.id||'',[['','Somente ao período'],...own.map(x=>[x.id,(x.inicio?V.format(x.inicio):'Abono')+' · '+x.dias_gozo+' d'])]);field('tipo','Tipo de documento','select','AVISO DE FERIAS',['AVISO DE FERIAS','RECIBO DE FERIAS','COMPROVANTE ASSINADO'].map(s=>[s,s]));field('link','Link HTTPS do arquivo real','url');field('observacao','Observação','textarea');note('Confira que o colaborador consegue abrir o link. Anexar não altera permissões do Drive e não cria um documento fictício.');}
function signedForm(d){form('Registrar retorno assinado',async()=>{await documentAction('assinado',{id:d.id,signed_link:values().signed_link});await saved('Devolução assinada registrada manualmente pelo RH.');});field('signed_link','Link HTTPS do arquivo devolvido assinado','url');note('Registre somente após conferir a devolução real. O sistema não verifica assinatura certificada; a integração Facilita Ponto ainda depende da API do fornecedor.');}
function sendForm(p,d){const e=currentEmployee,parts=launches.find(l=>l.id===d.lancamento_id),phone=(()=>{try{return RHDocuments.phone(e.whatsapp);}catch(_){return 'WhatsApp inválido';}})(),body='Olá, '+e.nome+'. Segue seu '+d.tipo.toLowerCase()+' referente ao período aquisitivo '+V.format(p.inicio)+' a '+V.format(p.fim)+(parts?.inicio?', com saída em '+V.format(parts.inicio):'')+': '+d.link+'\nPor favor, confira, assine e devolva o documento à empresa.';
 form('Conferir e autorizar mensagem',async()=>{if(phone==='WhatsApp inválido')throw Error('Corrija o WhatsApp no cadastro antes de enviar.');if(!confirm('Autorizar envio deste documento para '+e.nome+' ('+phone+')? Confirme o PDF e o acesso ao link.'))return;const id=d.delivery_id||await documentAction('preparar_envio',{id:d.id});await RH.result(client.rpc('rh_approve_delivery',{p_id:id,p_link:d.link,p_message:values().message}));await saved('Mensagem autorizada e colocada na fila. A entrega depende do processador e do n8n disponíveis.');});note('Destinatário: '+e.nome+' · '+phone);$('formFields').append(link('Conferir documento antes de enviar',d.link));field('message','Mensagem para WhatsApp','textarea',body);note('Só este botão de confirmação autoriza o envio. Aceite pelo n8n não comprova entrega ou assinatura. Intervalos seguem a fila existente.');$('submitForm').textContent='Autorizar envio';}
async function saved(text){$('formDialog').close();await refresh();message(text);}
$('editForm').onsubmit=e=>{e.preventDefault();$('submitForm').disabled=true;action(onSubmit);};$('closeForm').onclick=()=>{$('formDialog').close();$('submitForm').textContent='Salvar';};$('closeHistory').onclick=()=>$('historyDialog').close();$('addPeriod').onclick=periodForm;$('search').oninput=renderSummary;$('employeesFilter').onchange=renderSummary;$('statusFilter').onchange=renderSummary;$('refresh').onclick=()=>action(refresh);$('logout').onclick=()=>action(async()=>{await client.auth.signOut();location.href='login.html';});
$('exportHistory').onclick=()=>{const rows=[['Colaborador','CPF','Periodo_inicio','Periodo_fim','Direito','Gozados','Abono','Reservado','Saldo','Lancamento_inicio','Lancamento_fim','Dias_gozo','Dias_abono','Situacao','Observacao']];state(currentEmployee).line.forEach(p=>{const t=p.id?V.totals(p,launches):null;const entries=launches.filter(l=>l.periodo_id===p.id);const list=entries.length?entries:[{}];list.forEach(l=>rows.push([currentEmployee.nome,currentEmployee.cpf,p.inicio,p.fim,p.direito??'',t?.used??'',t?.sold??'',t?.reserved??'',t?.balance??'',l.inicio||'',l.fim||'',l.dias_gozo??'',l.dias_abono??'',l.status||(!p.id?'SEM REGISTRO':'RESUMO'),l.observacao||p.observacao||'']));});const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(';')).join('\r\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=link('',''+url);a.download='historico_ferias_'+RH.cleanCpf(currentEmployee.cpf)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
action(async()=>{profile=await RH.profile(client);await refresh();$('app').hidden=false;message('Selecione um colaborador para consultar o histórico ou registrar férias no período correto.');RH.watch(client,['rh_ferias_periodos','rh_ferias_lancamentos','rh_ferias_documentos'],()=>action(refresh));});
