const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function setup(allowed){const calls=[],ctx={console:{log(){}},ScriptApp:{AuthMode:{FULL:'FULL'},requireScopes(mode,scopes){calls.push(['scopes',mode,scopes]);if(!allowed)throw Error('consent required');},getProjectTriggers(){return [{getHandlerFunction:()=> 'processarFilaDriveRH'},{getHandlerFunction:()=> 'syncRH'}]},deleteTrigger(t){calls.push(['delete',t.getHandlerFunction()])},newTrigger(name){calls.push(['trigger',name]);return {timeBased(){return this},everyMinutes(n){calls.push(['minutes',n]);return this},create(){calls.push(['create'])}}}},DriveApp:{getRootFolder(){calls.push(['read']);return {getId:()=> 'root'}}}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(require.resolve('../RH_Drive_Automacoes.gs'),'utf8'),ctx);ctx.bancoDriveRH=(resource,method)=>{calls.push(['db',resource,method]);return [{}]};ctx.validarRaizesDriveRH=()=>calls.push(['validate']);return {calls,ctx};}
test('instalação exige escopo completo antes de criar gatilho',()=>{const {ctx,calls}=setup(false);assert.throws(()=>ctx.instalarAutomacaoDriveRH(),/consent/);assert.equal(calls.length,1);assert.equal(calls[0][2][0],'https://www.googleapis.com/auth/drive');});
test('instalação autorizada substitui apenas seu gatilho e mantém sincronização',()=>{const {ctx,calls}=setup(true);ctx.instalarAutomacaoDriveRH();assert.equal(calls[0][0],'scopes');assert.deepEqual(calls.filter(c=>c[0]==='delete'),[['delete','processarFilaDriveRH']]);assert(calls.some(c=>c[0]==='minutes'&&c[1]===5));assert(!calls.some(c=>c[0]==='delete'&&c[1]==='syncRH'));});
test('diagnóstico exige consentimento e não cria gatilho sem ele',()=>{const {ctx,calls}=setup(false);assert.throws(()=>ctx.diagnosticarAutomacaoDriveRH(),/consent/);assert.equal(calls.length,1);});
function reconcile(folders){const {ctx,calls}=setup(true),employee={id:'e',nome:'ANA MARIA SILVA',cpf:'52998224725'};ctx.bancoDriveRH=(r,m,q,body)=>{calls.push([r,m,body]);return r==='funcionarios_epi'?[employee]:[]};ctx.filhosDriveRH=id=>id==='active'?folders:[];ctx.apiDriveRH=()=>{throw Error('Mutação Drive não permitida no teste de vínculo')};return {ctx,calls};}
test('vínculo existente aceita nome sem CPF e não altera a pasta',()=>{const {ctx,calls}=reconcile([{id:'folderexisting1',name:'ANA MARIA SILVA',mimeType:'application/vnd.google-apps.folder'}]);ctx.executarTarefaDriveRH({funcionario_id:'e',link_only:true},{active_folder_id:'active',former_folder_id:'former'},Date.now()+1000);const post=calls.find(c=>c[0]==='rh_drive_links'&&c[1]==='post');assert.equal(post[2].folder_id,'folderexisting1');assert.equal(post[2].template_pending,false);});
test('pasta sem correspondência no modo vínculo não cria uma pasta vazia',()=>{const {ctx}=reconcile([]);assert.throws(()=>ctx.executarTarefaDriveRH({funcionario_id:'e',link_only:true},{active_folder_id:'active',former_folder_id:'former'},Date.now()+1000),/nenhuma pasta foi criada/);});
test('vínculo em lote bloqueia pastas homônimas',()=>{const {ctx}=reconcile([{id:'a',name:'ANA MARIA SILVA',mimeType:'application/vnd.google-apps.folder'},{id:'b',name:'ANA MARIA SILVA',mimeType:'application/vnd.google-apps.folder'}]);assert.throws(()=>ctx.executarTarefaDriveRH({funcionario_id:'e',link_only:true},{active_folder_id:'active',former_folder_id:'former'},Date.now()+1000),/homônimas/);});
